version: "3.5"

services:

  kali:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - root_homedir:/root

volumes:
  root_homedir:

#networks:
#  default:
#    name: dvwa_ciber
#    external: true
